### ISSUE TITLE
Cache control headers

### ISSUE THREAD

**Issue by arvgta** [arvgta/ajaxify#34] opened 2014-10-28 11:02 UTC
[Origin](https://github.com/arvgta/ajaxify/issues/30#issuecomment-58645272)

Problem:  The server-side `Cache control` headers are being ignored at the moment...

I thought of a solution in the meantime:
- Check for `Cache control` in the Ajax call.
- If set, then add the page URL to the `memoryoff` settings dynamically

@wikiloops: If you think it's fair (I'm not rich), I would like to reward you via PayPal for the _outstanding_ contributions.  Then please mail me at arvgta@gmail.com

Thanks!

**Comment by wikiloops** [comment] 2014-10-28 23:59
Hey there,
I have had little time lately, so my apologies for responding slowly.
I'm glad you notice the relevance of this issue, without giving long lectures here, let me try to give some helpfull hints again.

First of all, beware of what is the "cause" and what is the "symptom" of this issue - your approach is solving the symptom by disabling a feature that is enabled on default, after a certain criteria is detected.
Resolving the cause of this issue would be the other way around: disable the feature by default, and let those willing to live with the symptoms enable it :)

Secondly, mind that even pages with no caching directives sent from the domain's server will be likely to send at least some files that do send caching headers - those pulled from third party servers.
The http caching directives do not only apply to html pages, but may be distinct on any image, javascript, CSS etc etc transferred. 
As soon as there is any externally hosted scripts involved (adsense, facebook js, jquery, you name it), you will get some files with caching headers transferred along with a html file which may not have any. 
So, focusing on the pages headers only is still short of convenient.
I would not be surprised to learn that google would consider pseudo caching their adsense.js against their caching directives (20 minutes max) a violation of TOS, sorry to say so, but you have opened the box of pandorra by trying to offer a "set and forget" easy solution.

Last, just in case you are in need for a testing scenario, all you need to do to set caching directives is ad the following lines to your any .php test page, ideally before anything else is returned:

```
Header('Cache-Control: public, max-age=86400');

Header('Expires: '.gmdate('D, d M Y H:i:s \G\M\T', time() + 86400 ));
```

its not rocket science, really. 
If you watch what happens in p.e. Firebugs Network tab (make sure cache is not disabled by firebug or whichever dev tool you use!), you will see the file gets pulled from cache without any bite of webtraffic on the second visit... for exactly 86400 seconds to come.

**Comment by arvgta** [comment] 2014-10-29 08:06
Hey there!

Too bad... So I didn't find the "silver bullet" with my pseudo code.

> Resolving the cause of this issue would be the other way around: disable the feature by default
> and let those willing to live with the symptoms enable it :)

Just for clarity:  I would, of course, disable the feature by default...  Where is the difference of your approach?  And finally, what would the pseudocode look like?

> ...third party servers

I must admit, that I thought we wanted to handle entire pages, fetched by Ajax, ignoring everything else?

> caching their adsense.js

That would not be the case in my approach...

> testing scenario

Thanks for that.  Yes, I would have two possibilties:
- Host a couple of those pages on 4nf.org
- Link to an example site - [yours](http://www.wikiloops.com/)

I reckon, I don't understand your approach.  Could you maybe provide the pseudocode?

Thanks!

**Comment by wikiloops** [comment] 2014-10-29 10:31
a) my approach is just that - disabling memory, prefetch and deltas in ajaxify. Issue solved. I know it hurts.

b) the description of delta-mode states: 
"CSS’s and scripts that are common to both pages will remain in memory" - what I pointed out is: This seems to be ignoring the cache headers of those files! 
To fix this on the "symptom" side of ajaxify by applying a header check for any resource would be unbelievably complicated... 
One could use the quoted deltas-explanation to explain what the browser cache does: 
"CSS’s and scripts that are common to both pages will remain in the browser cache" has been true for quite some time and does not need any js to work.
The fact that deltas is ignoring caching directions on those files is less critical than the ignoring of html-page caching headers, simply because external CSS and JS is unlikely to come with a "no cache" directive, but I still feel the interference is not a good thing.

c) "handling entire pages" - I believe you will not find any page that serves all resources from its own domain (except the really big ones) - especially the toolkit users you are talking about will have lots of externally hosted plugins. 
Take 4nf.org as an example - you are pulling the jquery plugins from a CDN server, and they come with caching headers, while 4nf does not send any.

**Comment by arvgta** [comment] 2014-10-29 13:33
Thanks!

You're not the typical "Ajaxify" user, which must be taken into account.
The typical "Ajaxify" user has `deltas` and `memory` at least enabled.
The typical "Ajaxify" user wants the plugin to take over routine tasks automatically.

An analogy came to my mind:  It's a bit like the dualism between "automatic" cars and "manual" ones.
People who want more control at the price of more labour will prefer "manual" ones, whereas the typical "Ajaxify" user wants the script to take over the majority of, let's say, rather trivial or routine tasks.

Now, you seem to be ordering an "automatic" car but overhauling it to be a "manual" one -
that's an exotic use-case.

Especially `delta loading` is very popular amongst users.

So the scope of this issue would not be from the point of view of your use-case, but it would be great to provide a solution for the _typical_ Ajaxify user.

The only thing we have agreed upon so far, concerning this issue, is that the mechanism will be disabled at first.

> "handling entire pages"

Of course it makes sense to me in an Ajaxify environment.  There were several early requests from Ajaxify users to disable caching of pages selectively on the client-side.  This issue just does the same thing, however triggered from the server-side header.  i.e. After an Ajax call, the page will be selectively disabled in `$.memory()` for future calls, allowing for highly dynamic pages to be refreshed, indicated on the server-side.

Or am I thinking too simple?  At least that's what I thought, how this issue originated in #30 ?
Now, AFAI understand, all of a sudden, you're going down to the granularity of e.g. external resources, which I never perceived as part of the challenge.

Aren't these functionally dependent on whether the page is re-fetched or not, i.e.the re-fetched HTML?

What should we tackle first? #33 or this one?  (they both apply to a fair amount of users)

**Comment by wikiloops** [comment] 2014-10-29 17:00
I understand your line of argumentation about the "typical ajaxify user".

Lets seperate the `deltas` from the `memory` issue again - I agree the deltas issue is of less relevance for the reasons I stated.

So, as far as I see it, you have two choices now;
either disable `memory` by default and add a label "will override caching directives when enabled"
or
keep it enabled and implement the check for cache headers to turn it off after checking each individual page, as suggested in your initial post opening this issue.

If you choose the second approach to let your usual ajaxify customers enjoy the automatic ride while the unusual customers are happy their caching works as they expect it, you will be facing effects which you should take into account:
- to the "unusual" users with sophisticated caching ideas, the fixed memory function will "work" by constantly disabling memory over and over again, so from their point of view, this is unecessary code & time spent. No big deal maybe.
- for the "usual" ajaxify client who never worried about any of this, the proposed fix might actually turn into a downgrade: Assuming the user didnt do anything about caching headers, there is still a good chance caching headers will be present! This depends on the configuration of the server, which might have been done by someone who cares about this...
  Memory would not work with such a server configuration and the user would propably have no idea why thats so.
  So the only way to respect caching headers while using the memory feature is to analyze the directives more specificly than the presence check.
  I could outline how this check routine should be done, but I have strong doubts about the use of this compared to the much simpler solution a - disabling memory on default.

**Comment by arvgta** [comment] 2014-10-30 07:27
Disabling `memory` is a no-go for me, because the average user is happy with it.  The "unusual" user you outlined above is capable of disabling whatever he likes instead.

Thanks for your illustration of the `cache control` headers being set e.g. by the admin and without the awareness of e.g. the front-end developer!

> I could outline how this check routine should be done, but I have strong doubts about the use of 
> this compared to the much simpler solution a - disabling memory on default.

I don't have strong doubts, we should give it a try - here's some pseudocode:
- new plugin parameter `cacheControl` - default: `false`
- Ajax request returns `xhr` along with `Cache-Control`
- boolean expression as test
- if `true` -> disable in `$.memory()`

So we have two layers of "protection" against adverse affects:
- the default paramteter value of `false`
- the arbitrarily complex boolean expression (which is the only missing element of the solution)

So, can you think of a suitable boolean expression?
(it has to be rather tight, due to the "team-effect" you illustrated above...)

**Comment by wikiloops** [comment] 2014-10-30 12:06
Sorry to hear that that is your approach.
By creating the impression of "hey, its OK if your caching config is all messed up, ajaxify will solve that for you out of the box!", you are implying webmasters may safely stay unaware of this issue. 

When surfing a site as a human using a JS-ready browser, ajaxify will (before adding the fix) indeed solve the symptoms of a misconfigured caching directive, but all crawlers, spiders & bots will clearly recognize theres something odd about this page - thats why tools like pagespeed moan about that and advise to fix such things. 
One easy to understand example is: Googlebot will adjust its return/recrawl rate corresponding to caching directives - if a page says "I'm valid for a year to come!" it will get crawled less often than one signaling "I will have new content to crawl tomorrow!". What i am trying t say is: there is more than the UX side of things to be taken into acount here.

Browsers have different, complex ways of concluding how to handle the present headers and come to the "boolean expression" you are looking for, with IE being notorious to reaching different conclusions than other browsers... this is a very complex matter indeed.

I'll outline some of the logic for the sake of proving my point that this will either get rather messy or lead to disabling memory in 99% of all cases - you are looking for the `true / false` result of the general question "does this xhr response have a header set that looks as if someone purposely sends caching directives". OK then:

if `cache-control` header is present -> `true`
if `expires` header present -> `true`
if `last-modified` header present -> `true`
if `etag` header present -> `true`
else
we found a usecase for memory -> `false`

This still looks rather "tight" as you desired, since these headers may be the result of the basic server configuration and not intentionally set, chances of finding a usecase where none of the four is present are small. 
P.e. on 4nf.org, we have a last-modified header which was obviously not implemented on purpose and which will disable memory when following this logic... 

To set up a logic that can evaluate the question of "are those headers making sense, or is that a weird result of server config?" is way more complex, since each of those headers has a hierarchic weight.

I liked your analogy about cars btw - let me use it to express my point of view:
A car has one part that is generally intended to provide the motion (think caching), the motor (browser cache). There may be several variants of motors and different ways to start them, but they all do the same job, and every car comes with a motor by default. 
Now you are offering something to people who do not know how to use that motor, which is a nice thing to do. By building a second engine in the trunk of the car that does not need any knowledge to start, you are getting those people on the road.
In my case, my car suddenly stopped working after coming back from ajaxifies tuning shop, because your engine wasn't aware I might be one of those fellows who know how to start the original motor. 
I quickly worked that out and disabled `memory`, but I'll still have the weight of a second engine in my trunk... ;)
The fix we are making here is somewhat like "if the user touches the steering wheel or the ignition key, lets assume he knows how to start the motor and disable the trunk engine".

Dont get me wrong here - what I have been trying to point you at it: Your tool does a great job (otherwise I hadn't used it) UX wise. It may even be used to reduce webtraffic by huge percentages when implemented the `pulse`/`pronto idea` way we discussed - given that needs a more advanced "driver". 
So I see ajaxifys use range way beyond your "typical" audience. 
We have been solving some minor issues like the forms bug, which are usefull to any user. 
I'd strongly recommend keeping ajaxifies defaults in a way that does not need any action, neither by expert nor non-expert users, so a great first experience out-of-the-box is guaranteed regardless of scenario. 
A pro user realising "I am getting a trunk full of stuff of which I'll disable a lot right away" is worse than a hobby coder missing the fact that he might have actually benefitted from enabling memory IMO.
The benefit to that second category of users will actually be much greater if you DONT apply the header-check-fix discussed here, because ignoring the caching directives (which might not be set by the user) is exactly what is helping them right now.

**Comment by arvgta** [comment] 2014-10-31 06:15
So it's (usually) a situation of "Garbage In - Garbage Out" that would be the result?
I was thinking, that I'd disable the feature by default and document, that only the conscious user should enable it.  But you made quite clear that we're better off without the feature at all, because it could lead to unpredictable results, Ajaxify in the current form even "cushioning" any adverse effects!

So I won't implement the proposed solution :)

Your suggestion is to disable `memory` by default - as mentioned before, I do not want to do that, unless loads of users request it.

What is it that you need in terms of a "change request"?

EDIT:  You mentioned the `pulse` mechanism again.  Should we implement that, before going on?

**Comment by wikiloops** [comment] 2014-10-31 10:25
Alright then :)
I'm not going to try to reason again why I believe that keeping the `memory` on by default is not a wise decision. 
If you believe everyone who has trouble with it will take the time to let you know like I just did, then I'm affraid I can't share that approach.
From my experience unexpected behaviour like `memory` overriding my caching headers on default will let a thousand people leave in frustration before one actually gives you feedback about it, so it might be well advised to add some hints to at least the documentation.

As for the `pulse` mode - there is no need to do anything about it, it works like a charm without any change to ajaxify. You could add some dedicated documentation about how to use it, if you are at some point interested in attracting people who like to save bandwidth. 
You might make it easier to use by implementing the features I adressed, but none of them are necessary to let the basic concept of `pulse` work.

What I need in terms of a change request? Nothing :)
I have solved/met my demands a while ago and just reported what I ran into when doing that, so none of this here was ever intended to help ME, it was intended to improve ajaxify.  
Well, I can't do more than try, its your toy after all :) Good luck!

**Comment by arvgta** [comment] 2014-10-31 10:46
Hey :)

Thanks for the reply!  Thanks also for your altruistic ways...

> a thousand people leave in frustration before one actually gives you feedback about it

Yes, it's true, that the majority doesn't provide feedback.  
However, the simpler the issue, the more likely feedback will come - and what's simpler than requesting a change of default value, [like was done here](https://github.com/arvgta/ajaxify/issues/5#issuecomment-29199300).  I reacted by changing the default value...

I'm glad that you clarified, you don't need a change.  That was irritating me, because I couldn't quite figure out, what change you wanted.

Sure - go on, if you feel it's of benefit for some Ajaxify users.

I could, of course, disable `memory` by default, but there are two other things bothering me about it:
- I have sort of implicitly promised backward compatibility
- `memory, prefetch and preview` go hand in hand - I'd be pulling the plug on `prefetch` and `preview` as well in one go

Thanks very much!

**Comment by wikiloops** [comment] 2014-10-31 15:37
The two things that bother you are reasonable, and I'm glad you realized why I pulled the plug on exactly the features you named for my usecase.

When I introduced the `pulse` idea (called it "nerdmode") in #30, the initial idea included that
`pulse: true` would disable `prefetch` and `preview` by overriding the defaults. 
A little further down the line I summarized the pulse concept by saying
_Ajaxifys "memory" must be turned off to use it this way, so the "pulse" concept shows its strenghts in dynamic projects were no caching is applied to keep content fresh_

One could say there is no need for action, since I was able to work my way by discovering what needed to be disabled to let my project work, but my experience would have been way nicer if I had seen a default parameter labeled

```
pulse: false; /* advanced mode enabling server side cache control & added traffic saving options, default:false */
```

benefits:
- Any unadvanced user could stay clear of it and enjoy the enabled memory default setting, 
- there would be some promising looking thing to enable for people like me, who are also capable of reading documentation of pulse to find out about the traffic saving things... That experience is psychologically a lot nicer than noticing one will have to disable some very promoted features to be able to use ajaxify.

See it as a question of promotion/documentation if you wish!
"There is a second gear to shift to for experienced developers" is cooler than saying "you might have to disable prefetch, preview and memory if your project is dynamic and has caching settings." - and I feel one of the two statements should be added to the documentation :)

**Comment by arvgta** [comment] 2014-10-31 16:43
Hey :)  Thanks for explaining that further!

You're right - from a marketing point of view - it sounds like an addition, while actually subtracting logic :)

What are the requirements of `nerdmode` ? (I would like to call it that way after all)
- `preview` is disabled already by default (but can be overridden for good programmatically once more)
- `prefetch` and `memory` have to be disabled, too (programmatically)

(That's not exactly rocket-science - if that's it, I could try that straight-away)

What else?  _Is there need for sending a parameter on every Ajax request (for the advanced user)_?

**Comment by wikiloops** [comment] 2014-11-01 16:57
requirements for an appealing marketing to more experienced users are:
- a non-offensive name for the feature (c'mon, `nerdmode` was a joke!)
- a well structured documentation suitable to people coding dynamic content & optimizing for speed / traffic reduction (mobile).

the xtra parameter would be "sugar on top of the candy" as I have pointed out before, so, no, that's not required IMO. 

I am not absolutely sure if it wouldn't  be wise to also disable `deltas` within the override-by-`pulse` - I ended up disabling it for my usecase. 
I guess its OK to leave it enabled, an experienced user will understand the possible problematics of combining deltas & pulse, what you will basicly achieve by introducing pulse is getting people interested to try ajaxify, and those willing to read the docs and do some implementation work to use the promoted benefits of `pulse` will propably not be overwhelmed by this. 

No need to rush anything, the whole concept is only worth something when there is some good to read & good to google documentation on it :)

**Comment by arvgta** [comment] 2014-11-02 09:21
Alright - we'll call it `pulse` after all.

[Enabled in this file only](http://4nf.org/ajaxify.js)

Please test, by setting:

`pulse: true`

I've introduced a basic description here 
- http://4nf.org/interface/ 

briefly, but haven't tested it yet...

What does it do?
- disable `memory` and `prefetch` programmatically.

Am wondering, whether to disable `preview` programmatically, too, just in case?

Have also allocated a [dedicated page "Pulse"](http://4nf.org/pulse/) for the feature, because its documentation will probably be lengthy?

Thanks!

**Comment by wikiloops** [comment] 2014-11-02 12:49
- maybe it would make sense to seperate the default parameters display by categories:

```
{
/* basic config parameters */
    selector : "a:not(.no-ajaxy)", //Selector for elements to ajaxify - without being swapped - e.g. a selection of links
    forms : "form:not(.no-ajaxy)", // jQuery selection for ajaxifying forms - set to "false" to disable
    canonical : true, // Fetch current URL from "canonical" link if given, updating the History API.  In case of a re-direct...

/* visual effects settings */
    requestDelay : 0, //Delay of Pronto request
    fade : 0, //in msec - fade in/out
    pop: 0, //in msec - pop effect in both dimensions
    squeeze: 0, //in msec - slide/squeeze effect, first left then right
    previewoff : true, // Plugin previews prefetched pages - set to "false" to enable or provide a jQuery selection to selectively disable

/* script and style handling settings, prefetch */
    deltas : true, // true = deltas loaded, false = all scripts loaded
    inline : true, // true = all inline scripts loaded, false = only specific inline scripts are loaded
    inlinehints : false, // strings - separated by ", " - if matched in any inline scripts - only these are executed - set "inline" to false beforehand
    style : true, // true = all style tags in the head loaded, false = style tags on target page ignored
    prefetch : true, // Plugin pre-fetches pages on hoverIntent or touchstart

/* debugging & advanced settings*/
    verbosity : 0,  //Debugging level to console: 1 = medium, 2 = verbose
    memoryoff : false, // strings - separated by ", " - if matched in any URLs - only these are NOT executed - set to "true" to disable memory completely
    cb : null, // callback handler on completion of each Ajax request - default null
    pulse: false; // advanced mode enabling server side cache control & added traffic saving options
    pluginon : true // Plugin set "on" or "off" (==false) manually
}
```

since I'd put "preview" in the visual category, it might be left unrelated to the pulse mode - question remains: does preview work with prefetch & memory disabled?
- Don't get me wrong, but: Please do not continue to attempt assigning me with tests, I am sure you can do it, thank you :) 
- the length of the pulse documentation will not be overwhelming if one assumes the reader knows speed tests, how caching works, knows a little javascript and is used to actually working within code. Catering to people without that knowledge will turn into a lenghty "how to code a decent webpage" tutorial, and I dont think you'd like to go there. I am not sure I have understood the benefit of having the (empty) pulse page live on 4nf.org at this moment, tbh.

sidenote: 4nf.org navigation has a bug, error occurs when trying to navigation item "home" or hovering over the logo on a sub-page...

**Comment by arvgta** [comment] 2014-11-02 16:53
Hey :)

Your new interface description was so good, that I simply cut & pasted it onto :
- http://4nf.org/interface/

No, `preview` doesn't work without `memory` and `prefetch` - have just tested!
There is no hard crash or anything, but simply no `preview` effect...
So I reckon, I'll programmatically disable that, too?

Also briefly tested `pulse` on 4nf.org _without_ the server-side configuration, however.
It works, that's to say, doesn't cause any errors... (tested on Firefox and Chrome)

Didn't mean to bother you with the testing.  It's just that it's valuable, when somebody else than the author tests...

I couldn't seem to reproduce the "home button" bug.
Only thing I noticed was that in Firefox, with the console open, there is weird behavior, not, however when the console is closed.   On Chrome, no errors whatsoever.

So, we'll be assuming expert users only as the target group for the `pulse` feature, which means that the explanation / documentation can be more cryptive than I orginally thought...

Thanks!

**Comment by arvgta** [comment] 2014-11-04 13:39
Hey,

just added your splendid site to this [demos page](http://4nf.org/demos/).

I noticed your call looks like this:

```
jQuery(“#content”).ajaxify({style:false, forms:”form:not(.no-ajaxy)”, cb:jaxed, delta:false});
```

(a few parameters, that are defaults omitted)

Look carefully at this bit: `delta: false` - the parameter should be `deltas: false`

That might mean that deltas are enabled on http://www.wikiloops.com/ !?

Just thought I'd let you know, because it looks like a misunderstanding...

Cheers!

**Comment by wikiloops** [comment] 2014-11-04 21:40
Will have a look, thanks for pointing me at this! Since I moved most of the inline scripts out of the content div and am preventing a second output with pulse, deltas will propably have little to do even if enabled, but I'll check it out for sure.

I noticed you added adsense on 4nf.org - well done. The navigation bug in firefox i mentioned does still occur to me tho, even without console/firebug opened.

**Closed as completed** 2014-11-06 10:40 UTC
