### ISSUE TITLE
Double entries of inline scripts

### ISSUE THREAD

**Issue by menturion** [arvgta/ajaxify#202] opened 2020-04-22 14:53 UTC
I am getting double entries of inline scripts (of class "ajy-inline") due to this line of code ...
https://github.com/arvgta/ajaxify/blob/3ecb0078308dd25497d6e3869a355d315a62849c/ajaxify.js#L359

**Comment by arvgta** [comment] 2020-04-24 16:28
After hours of work, we could not reproduce the bug at all... Closing...

Please refrain from spawning new issues.

**Closed as completed by arvgta** 2020-04-24 16:28 UTC
